### ISSUE TITLE
Debugging within Nose

### ISSUE THREAD

**Issue by KyleJamesWalker** [AntoineD/nose-pudb#2]
I was wondering if this plugin exposes a way to jump into the debugger (non-post-mortum), if I create the below function I can stop before a crash and then walk down into the function that had the error. So just wondering if there's a way already, and if not I can look into making a PR with this support.

``` python
def set_trace():
    """Call pdb.set_trace in the calling frame, first restoring
    sys.stdout to the real output stream. Note that sys.stdout is
    NOT reset to whatever it was before the call once pdb is done!
    """
    import pudb
    import sys
    stdout = sys.stdout
    sys.stdout = sys.__stdout__
    pudb._get_debugger().set_trace(sys._getframe().f_back)
set_trace()
```

I modified the code from:

``` python
from nose.tools import set_trace; set_trace()
```

When I ran this line `from pudb import set_trace; set_trace()` I get a horrible stack trace.

**Comment by vishnubob** [comment]
I came here looking for the same information.  Thanks KyleJamesWalker for the snippet.
